package ch.unibas.dmi.dbis.fds.kotlin

enum class MessageType {
    GET, GET_RESPONSE,
    SET, SET_RESPONSE,
    LOOKUP, LOOKUP_RESPONSE,
    CHORD_GET_SUCCESSOR, CHORD_GET_SUCCESSOR_RESPONSE,
    CHORD_GET_PREDECESSOR, CHORD_GET_PREDECESSOR_RESPONSE,
    CHORD_SET_PREDECESSOR, CHORD_SET_PREDECESSOR_RESPONSE,
    CHORD_FIND_SUCCESSOR, CHORD_FIND_SUCCESSOR_RESPONSE,
    CHORD_FIND_PREDECESSOR, CHORD_FIND_PREDECESSOR_RESPONSE,
    CHORD_CLOSEST_PRECEDING_FINGER, CHORD_CLOSEST_PRECEDING_FINGER_RESPONSE,
    CHORD_NOTIFY, CHORD_NOTIFY_RESPONSE,
    CHORD_STABILIZE, CHORD_STABILIZE_RESPONSE
}
